// Generated by LiveScript 1.2.0
(function(){
  var requires;
  requires = require('./requires');
  module.exports = {
    Mw: {
      base: requires.file('mw/base_mw'),
      registry: requires.file('mw/registry')
    },
    Runner: {
      base: requires.file('runner/base_runner')
    },
    middleware: function(ctx){
      return new Middleware(ctx);
    },
    Middleware: requires.file('middleware')
  };
}).call(this);
